# .travis.yml
language: node_js
node_js:
  - "6"
env:
  global:
    - NPM_VERSION="^3.0.0"
matrix:
  include:
    - node_js: "6"
      env:
    - node_js: "8"
      env:
before_install:
  - "npm i -g npm@\"$NPM_VERSION\""
notifications:
  email: false
